### ISSUE TITLE
Namespace on routes

### ISSUE THREAD

**Issue by leonardoprg** [genkirb/genki#32]
### Description

On controller I would like to define namespaces:

```
class HomeController < Genki::Controller

  namespace '/home' do

    get '/hello' do
      render "Hello World"
    end

  end

end
```

It needs to generate a route `/home/hello`

**Comment by diego-silva** [comment]
When I suggested namespace was the first name that came up on my mind, but we can use a different one.

**Comment by leonardoprg** [comment]
maybe `scope`, let's think which one makes more sense.
