### ISSUE TITLE
Search for how will work DataMapper/ActiveRecord

### ISSUE THREAD

**Issue by diego-silva** [genkirb/genki#4]
### Description

We need to understand how will work DataMapper, and how make it simple.
- [x] Active Record
- [x] DataMapper

**Comment by leonardoprg** [comment]
http://datamapper.org/why.html

**Comment by diego-silva** [comment]
Maybe we should just make sure gems like `activerecord`, `sequel` and `data_mapper` works

**Comment by leonardoprg** [comment]
Sure,

we can ask to user on `genki new` if would like to use  `active record`, `sequel`, `data_mapper` or nothing. sometimes people just wanna a site without database.
